# Generated by Django 5.0.6 on 2024-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbehavior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior',
            name='browser_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userbehavior',
            name='ip_address',
            field=models.GenericIPAddressField(default={}),
            preserve_default=False,
        ),
    ]
